### ISSUE TITLE
Incompatibility with Syncmatica

### ISSUE THREAD

**Issue by zcyl2** [senseiwells/ServerReplay#23] opened 2024-04-01 10:39 UTC
serverreplay跟Syncmatica 在minecraft 1.20.4 的网络协议会导致不兼容，导致syncmatica mod无法使用。

**Comment by senseiwells** [comment] 2024-04-01 16:11
Please submit your report in English.

**Comment by disymayufei** [comment] 2024-04-13 14:00
He means: this mod for Minecraft 1.20.4 has a network protocol incompatibility issue with the syncmatica mod, which causes the syncmatica do not work after installed this mod.

**Comment by Redappleyyds** [comment] 2024-04-24 21:48
in 1.20.2 too

**Comment by Dango0706** [comment] 2024-04-26 06:54
Use Google Translate for the following words

It does conflict with syncmatica, attached are the server and client logs.

[server.log](https://github.com/senseiwells/ServerReplay/files/15126438/server.log)
[client latest.log](https://github.com/senseiwells/ServerReplay/files/15126442/client.latest.log)

**Comment by senseiwells** [comment] 2024-05-10 17:52
The crash you have attached is a separate issue, it is an issue with voice chat.

**Comment by senseiwells** [comment] 2024-05-11 17:01
I cannot reproduce this issue.
I installed [syncmatica-1.20.4-0.3.11](https://github.com/sakura-ryoko/syncmatica/releases/tag/1.20.4-0.3.11) with the latest version of server replay.

I was able to boot up the server, record a player, and view the replay with ReplayMod.

Please provide more details for this issue; a list of mods you are using, versions of the mods in question, a replay file if applicable, any logs and crash reports. Otherwise I will close it as invalid.

**Comment by Redappleyyds** [comment] 2024-05-19 22:52
1.20.2版本的Server Replay和Syncmatica也有此问题

Server Replay and Syncmatica version 1.20.2 also have this issue

（Google translate）

**Comment by senseiwells** [comment] 2024-06-17 21:12
This is more of a Syncmatica issue, you can keep track of that issue here: https://github.com/End-Tech/syncmatica/issues/74

**Comment by mcbianxiao** [comment] 2024-08-13 05:06
> 我无法重现此问题。我安装了 [syncmatica-1.20.4-0.3.11](https://github.com/sakura-ryoko/syncmatica/releases/tag/1.20.4-0.3.11) 和最新版本的服务器回放。
> 
> 我能够启动服务器，录制播放器，并使用ReplayMod查看回放。
> 
> 请就此问题提供更详细的详情。您正在使用的模组列表、相关模组的版本、重播文件（如果适用）、任何日志和崩溃报告。否则，我将将其关闭为无效。

In addition, both the Mod is installed on the 1.21 version of the server at the same time, also can cause IndexOutofBoundsException error.  However, the server did not give any error.

**Comment by mcbianxiao** [comment] 2024-08-13 17:02
> I cannot reproduce this issue. I installed [syncmatica-1.20.4-0.3.11](https://github.com/sakura-ryoko/syncmatica/releases/tag/1.20.4-0.3.11) with the latest version of server replay.
> 
> I was able to boot up the server, record a player, and view the replay with ReplayMod.
> 
> Please provide more details for this issue; a list of mods you are using, versions of the mods in question, a replay file if applicable, any logs and crash reports. Otherwise I will close it as invalid.

In addition, both the Mod is installed on the 1.21 version of the server at the same time, also can cause IndexOutofBoundsException error.  However, the server did not give any error.
However, after I applied the pull requests: https://github.com/sakura-ryoko/syncmatica/pull/4 , the problem seems to be solved

**Closed** 2024-08-18 23:12 UTC

**Comment by TopazYC** [comment] 2025-07-09 12:17
I met the same problem in mc 1.18.2, with ServerReplay 1.1.5 + Syncmatica 0.3.11 ( End-Tech's repo).
The completion of channel seems different in End-Tech's repo (which applies to 1.19-) and in sakua-ryoko's repo (which applies to 1.20+) so I cannot directly apply the pull request of [Autumn-Leaf620](https://github.com/Autumn-Leaf620) in [sakura-ryoko/syncmatica#4](https://github.com/sakura-ryoko/syncmatica/pull/4).
How may I modify the code in End-Tech/Syncmatica to make them compatible? (It seems that I need to modify some codes in /src/main/java/ch/endte/syncmatica/network/ChannelManager.java but I don't know how)

**Comment by senseiwells** [comment] 2025-07-09 12:22
Read the issue report submitted to the end tech repo above. This will not be fixed on server replays side as this version is no longer being maintained.
