### ISSUE TITLE
Player predicate error

### ISSUE THREAD

**Issue by memorydream** [senseiwells/ServerReplay#22] opened 2024-03-30 17:26 UTC
Hi , I tried use "has_name" predicate for record player , but I got "Tried to get player before player joined"

Server running 1.20.1 , Carpet , Velocity and ServerReplay-1.0.7+mc1.20.1

I use it like this
- set player predicate
```
  "player_predicate": {
    "type": "has_name",
    "names": [
      "Recorder"
    ]
  },
```
- `/replay reload`
- `/player Recorder spawn`
- get error and message "Started replay for Recorder" , and do not spawn fake player

I do something wrong?

**Comment by senseiwells** [comment] 2024-03-30 17:29
This is almost certainly caused by Carpet, see https://github.com/gnembon/fabric-carpet/pull/1849.
Unfortunately this will only be fixed in future versions of carpet and there's not much I can do about it, sorry.

**Closed by senseiwells** 2024-03-30 17:29 UTC
