### ISSUE TITLE
Replay Mod gets stuck on Please Wait when skipping in long replays.

### ISSUE THREAD

**Issue by VaibhavVerma21** [senseiwells/ServerReplay#36] opened 2024-05-22 20:02 UTC
Unsure if this is a ServerReplay problem or how replay mod handles replays. But when trying to view a long replay, in my case of a perimeter, the screen was stuck on either Please Wait or game crashed. Never tried to record that long of an replay on my client using replay mod.

**Comment by senseiwells** [comment] 2024-05-23 13:12
This is an issue with ReplayMod technically - but it was never really designed to playback such long replays, so it'll probably be marked as working as intended.
You can counter act this in ServerReplay already by setting a max duration, or max file size and automatically restarting the replay after.

**Closed by senseiwells** 2024-05-23 13:12 UTC

**Comment by VaibhavVerma21** [comment] 2024-05-24 23:28
I am unsure of how long the replay must be for it to not crash. I will read the docs for finding out how to restart it after certain time/size but if you can tell me, it will be great.

Also is there any alternative way to do what one can do using server replay and replay mod to achieve the cinematography it offers?

**Comment by senseiwells** [comment] 2024-05-25 20:06
There isn't some fixed hardcoded number baked into ReplayMod. It depends on the performance of your computer, if you have a really powerful computer you can make large skips and it'll be able to process it.

To your second question. I have no idea.
