### ISSUE TITLE
Error on Console

### ISSUE THREAD

**Issue by GamerTable** [senseiwells/ServerReplay#39] opened 2024-06-07 17:49 UTC
https://mclo.gs/lD8pJ25
This keeps showing up when I log out of the server.
Using latest versions of Simple Voice Chat and Server Replay 1.20.1

The server doesn't crash or anything but idk, thought it might be worth looking into.

**Comment by senseiwells** [comment] 2024-06-17 18:47
Thank you for the report, this is a duplicate of #35

**Closed by senseiwells** 2024-06-17 18:47 UTC
